### PR TITLE
Make indentation consistent

### PR DESCRIPTION
**Pull request by bvtsang**
The thing to watch out for is that there are mixed spaces and tabs between each field and its corresponding comment.

### CODE REVIEW

**Comment by Wolvan** [comment]
Very good fix, @bvtsang :laughing: 
image

**Comment by bvtsang** [comment]
This is what I see:

screen shot 2016-02-10 at 11 49 45 am

And yeah, this whole indentation thing is wonky.

As an alternative, we could either do:

```
title: Title goes here # {string} required - Title of the message
author: Your name # {string} optional - Name of the author
...
```

or

```
# {string} required - Title of the message
title: Title goes here
# {string} optional - Name of the author
author: Your name
...
```

or force the indentation with spaces.

**Comment by bvtsang** [comment]
Okay, I went with spaces. That should definitely fix everything.

**Comment by Wolvan** [comment]
That seems to work. Thanks @bvtsang

**Pull request merged**
